### ISSUE TITLE
Dockerfile Layer Fix

### ISSUE THREAD

**Issue by MatthewEdge** [FrankKerschbaumer3/kube-flask#1]
https://github.com/FrankKerschbaumer3/kube-flask/blob/49722a8f5f77ee00cc185d34f8ee07c9aa986db9/artillery/Dockerfile#L5

You can condense these lines to one so you don't create extra layers in the Docker image:

`RUN npm install artillery artillery-plugin-faker`

**Comment by FrankKerschbaumer3** [comment]
Gratzi
